[build-system]
requires = ["scikit-build-core"]
build-backend = "scikit_build_core.build"

[project]
name = "raylib-w-py"
version = "0.1.0"

[tool.scikit-build]
build-dir = "build"
wheel.packages = ["src/raylib", "src/raylibwpy"]
cmake.verbose = true